### Dealing with Duplicate data and Missing Value

In [2]:
import pandas as pd
import numpy as np

Duplicate Data

In [3]:
cdata = pd.read_csv("Subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [11]:
cdata.duplicated()
#Check emp id
cdata['EEID'].duplicated()
cdata['Name'].duplicated()
#Drop Data
cdata['EEID'].drop_duplicates()

0    EMP01
1    EMP02
2    EMP03
4    EMP05
5    EMP06
Name: EEID, dtype: str

In [5]:
#Find null values
cdata.isnull().sum()
#Element
cdata.dropna()

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [25]:
#Replace Nan with any value
cdata.replace(np.nan, "EmptyData")
cdata['salary'].replace(np.nan,5000)
#Replace Nan in salary with mean value
mean = np.mean(cdata['salary'])
cdata['salary'].replace(np.nan, mean)
#Method 1
cdata['salary'] = cdata['salary'].fillna(mean)
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0

In [28]:
cdata = pd.read_csv("Subdata_pandas/company.csv")
cdata
#Forward Fill previous row
cdata.ffill()
#Backward Fill previous row
cdata.bfill()

    EEID      Name gender   salary
0  EMP01    ayushi      F  25000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  25000.0
6  EMP02     rohit      M  25000.0