##  Compare,Pivoting & Melting DataFrame

In [39]:
import pandas as pd

Compare

In [40]:
shop_7Oct = {
    "Fruits":['Mango','Apple','Banana','Papaya'],
    "Price":[150,200,60,25],
    "Quantity":[15,7,12,13]
}
Stock_7Oct= pd.DataFrame(shop_7Oct)

shop_8Oct = {
    "Fruits":['Mango','Apple','Banana','Papaya'],
    "Price":[200,250,60,35],
    "Quantity":[15,17,24,15]
}

Stock_8Oct=pd.DataFrame(shop_8Oct)
Stock_8Oct

   Fruits  Price  Quantity
0   Mango    200        15
1   Apple    250        17
2  Banana     60        24
3  Papaya     35        15

In [41]:
Stock_7Oct.compare(Stock_8Oct)
Stock_7Oct.compare(Stock_8Oct,align_axis=0)
Stock_7Oct.compare(Stock_8Oct,keep_equal=True)
Stock_7Oct.compare(Stock_8Oct,keep_shape=True)
Stock_7Oct.compare(Stock_8Oct,align_axis=0,keep_shape=True,keep_equal=True)

         Fruits  Price  Quantity
0 self    Mango    150        15
  other   Mango    200        15
1 self    Apple    200         7
  other   Apple    250        17
2 self   Banana     60        12
  other  Banana     60        24
3 self   Papaya     25        13
  other  Papaya     35        15

In [42]:
monthly_shop = {
    "Product":['Laptop','Mobile','Laptop','Mobile','Laptop','Laptop'],
    "Month":["Jan","Jan","Feb","Feb","Mar","Apr"],
    "Price":[50000,27500,65000,45000,95000,35000]
}

monthly_sales = pd.DataFrame(monthly_shop)
monthly_sales

  Product Month  Price
0  Laptop   Jan  50000
1  Mobile   Jan  27500
2  Laptop   Feb  65000
3  Mobile   Feb  45000
4  Laptop   Mar  95000
5  Laptop   Apr  35000

In [43]:
monthly_sales.pivot(
    index = "Product",
    columns="Month",
    values="Price"
)

Month        Apr      Feb      Jan      Mar
Product
Laptop   35000.0  65000.0  50000.0  95000.0
Mobile       NaN  45000.0  27500.0      NaN

In [44]:
monthly_sales.pivot_table(values="Price",index="Product",columns="Month",aggfunc="sum")

Month        Apr      Feb      Jan      Mar
Product
Laptop   35000.0  65000.0  50000.0  95000.0
Mobile       NaN  45000.0  27500.0      NaN

In [45]:
monthly_shop1 = {
    "Product":['Laptop','Mobile','Laptop','Mobile','Laptop','Laptop'],
    "Month":["Jan","Jan","Feb","Feb","Mar","Mar"],
    "Price":[50000,27500,65000,45000,95000,35000]
}

monthly_sales1 = pd.DataFrame(monthly_shop)
monthly_sales1

  Product Month  Price
0  Laptop   Jan  50000
1  Mobile   Jan  27500
2  Laptop   Feb  65000
3  Mobile   Feb  45000
4  Laptop   Mar  95000
5  Laptop   Apr  35000

In [46]:
monthly_sales.pivot_table(values="Price",index="Product",columns="Month",aggfunc="sum")

Month        Apr      Feb      Jan      Mar
Product
Laptop   35000.0  65000.0  50000.0  95000.0
Mobile       NaN  45000.0  27500.0      NaN

In [48]:
shop_sales = {
    "product" : ['Laptop','Mobile','Mouse'],
    "Jan" : [67500,25000,950],
    "Feb" : [87000,35000,850],
    "Mar" : [98000,23500,650]
}
sales = pd.DataFrame(shop_sales)

sales.melt(
    id_vars = "product",
    var_name = "Month",
    value_name = "Sales"
)

  product Month  Sales
0  Laptop   Jan  67500
1  Mobile   Jan  25000
2   Mouse   Jan    950
3  Laptop   Feb  87000
4  Mobile   Feb  35000
5   Mouse   Feb    850
6  Laptop   Mar  98000
7  Mobile   Mar  23500
8   Mouse   Mar    650