### GroupBy & MergeorJoin

In [4]:
import pandas as pd

In [5]:
exp = pd.read_excel("Subdata_pandas/expense.xlsx")
exp

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04        Food              Zomato     257          NaN
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000          UPI
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50          NaN
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          NaN
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000          NaN
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

In [6]:
#Find the total expense for each category
#M1
exp.groupby("Category")["Amount"].sum()
#M2
exp.groupby("Category")["Amount"].agg(['sum'])

#Give a complete expense summary for each category
exp.groupby("Category")["Amount"].agg(
    ['sum','count','mean','max','min']
)

              sum  count         mean    max   min
Category
Bills       18724      3  6241.333333  16000  1074
Clothes      2890      2  1445.000000   1890  1000
Essentials   4485      7   640.714286   1500    50
Food         3022      9   335.777778    890    10
Grocery      1028      8   128.500000    456    26

In [7]:
# How much money was paid using cash,card and Card?
exp.groupby("Payment Mode")["Amount"].agg(['sum'])
# How many transactions were made using each payment mode?
exp.groupby("Payment Mode")["Amount"].agg(['count'])

              count
Payment Mode
Card              1
Cash              8
UPI              16

In [8]:
#for each category how much amount spent using card,cash & UPI
exp.groupby(['Category','Payment Mode'])["Amount"].agg(['sum'])

#For each payment mode,calculate the total amount spent across categories
exp.groupby(['Payment Mode','Category'])["Amount"].agg(['sum'])

                           sum
Payment Mode Category
Card         Food          780
Cash         Essentials   3415
             Food          530
             Grocery       692
UPI          Bills       18724
             Clothes      1890
             Essentials    900
             Food         1455
             Grocery       336

In [9]:
#which categories have the highest total expense
exp.groupby('Category')['Amount'].agg('sum').sort_values(ascending=False)
#create a Dataframe containing the total expense of each category
exp.groupby('Category')['Amount'].sum().reset_index(name="Total Expense")

     Category  Total Expense
0       Bills          18724
1     Clothes           2890
2  Essentials           4485
3        Food           3022
4     Grocery           1028

In [ ]:
#----Task----

#Create a DataFrame containing the total expense of each category
#What is the average transaction amount for each payment mode?
#Find the highest individual transaction in each category
#Show total, average, minimum and maximum transaction amount for each payment mode

# Join OR Merge

In [10]:
Customer = pd.read_csv("Subdata_pandas/customer.csv")
Customer
payment = pd.read_csv("Subdata_pandas/payment.csv")
payment

   customerid  amount            mode paymentdate
0           1      60            Cash  2020-09-24
1          11      80            Cash  2021-03-01
2           2     500     Credit Card  2020-04-27
3           8     100            Cash  2021-01-26
4           7      20  Mobile Payment  2021-02-01
5          17     250     Credit Card  2021-04-01
6          10      70  Mobile Payment  2021-02-28

In [ ]:
#Inner Join
pd.merge(Customer,payment,on="customerid", how="inner")

   customerid firstname lastname address  amount         mode paymentdate
0           1      Mary    Smith   Delhi      60         Cash  2020-09-24
1           2     Madan    Mohan  Mumbai     500  Credit Card  2020-04-27
2          17         R   Madhav     Goa     250  Credit Card  2021-04-01

In [ ]:
#Left Join
pd.merge(left=Customer,right=payment,on="customerid",how="left")

   customerid firstname  lastname  address  amount         mode paymentdate
0           1      Mary     Smith    Delhi    60.0         Cash  2020-09-24
1           3     Linda  Williams    Udupi     NaN          NaN         NaN
2           4   Barbara     Jones  Chennai     NaN          NaN         NaN
3           2     Madan     Mohan   Mumbai   500.0  Credit Card  2020-04-27
4          17         R    Madhav      Goa   250.0  Credit Card  2021-04-01

In [ ]:
#Right Join
pd.merge(left=Customer,right=payment,on="customerid",how="right")

   customerid firstname lastname address  amount            mode paymentdate
0           1      Mary    Smith   Delhi      60            Cash  2020-09-24
1          11       NaN      NaN     NaN      80            Cash  2021-03-01
2           2     Madan    Mohan  Mumbai     500     Credit Card  2020-04-27
3           8       NaN      NaN     NaN     100            Cash  2021-01-26
4           7       NaN      NaN     NaN      20  Mobile Payment  2021-02-01
5          17         R   Madhav     Goa     250     Credit Card  2021-04-01
6          10       NaN      NaN     NaN      70  Mobile Payment  2021-02-28