##  Compare,Pivoting & Melting DataFrame

In [2]:
import pandas as pd

Compare

In [3]:
shop_7Oct = {
    "Fruits":['Mango','Apple','Banana','Papaya'],
    "Price":[150,200,60,25],
    "Quantity":[15,7,12,13]
}
Stock_7Oct= pd.DataFrame(shop_7Oct)

shop_8Oct = {
    "Fruits":['Mango','Apple','Banana','Papaya'],
    "Price":[200,250,60,35],
    "Quantity":[15,17,24,15]
}

Stock_8Oct=pd.DataFrame(shop_8Oct)
Stock_8Oct

   Fruits  Price  Quantity
0   Mango    200        15
1   Apple    250        17
2  Banana     60        24
3  Papaya     35        15

In [7]:
Stock_7Oct.compare(Stock_8Oct)
Stock_7Oct.compare(Stock_8Oct,align_axis=0)
Stock_7Oct.compare(Stock_8Oct,keep_equal=True)

  Price       Quantity
   self other     self other
0   150   200       15    15
1   200   250        7    17
2    60    60       12    24
3    25    35       13    15